[package]
name = "rs_1brc"
version = "0.2.19"
edition = "2024"
description = "The One Billion Row Challenge for RUST"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
concat-idents = "1.1.5"
fork = "0.6.0"
indicatif = "0.18.3"
libc = "0.2.180"
proc-cpuinfo = "0.2.0"
rayon = "1.11.0"

[features]
hit_miss = []

[profile.release]
panic = "abort"
debug = true
lto = true
opt-level = 3
